"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowRight,CheckCircle2,Home,MapPin,Menu,Phone,Search,ShieldCheck,Sparkles,X} from "lucide-react";
import InquiryForm from "./components/InquiryForm";
const phone="+919876543210",wa="https://wa.me/919876543210?text=Hi%20I%27m%20interested%20in%20a%20property%20on%20LRJ%20Properties.";
const slides=[
{image:"https://images.pexels.com/photos/7031581/pexels-photo-7031581.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",title:"Find Your Dream Property",accent:"in Laksar",text:"Buy, sell, or rent — houses, plots, flats, and commercial spaces. Your trusted local real estate partner in Haridwar, Uttarakhand."},
{image:"https://images.pexels.com/photos/7031594/pexels-photo-7031594.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",title:"Invest in Your Future",accent:"with Confidence",text:"Prime residential plots and ready-to-move houses in the best localities of Laksar and Haridwar."},
{image:"https://images.pexels.com/photos/7031600/pexels-photo-7031600.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",title:"A Better Place to",accent:"Call Home",text:"Explore practical homes, land and local property opportunities with straightforward guidance."},
{image:"https://images.pexels.com/photos/7031581/pexels-photo-7031581.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",title:"Sell or Rent",accent:"Your Property",text:"List your property with us and connect directly with local buyers and tenants."}];
const props=[
["Residential Plot","Residential Plot — Laksar","Laksar, Haridwar","1,200 sq ft","https://images.pexels.com/photos/7031581/pexels-photo-7031581.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1000&h=700"],
["Independent House","Family Home — Roorkee Road","Laksar, Haridwar","1,650 sq ft","https://images.pexels.com/photos/7031594/pexels-photo-7031594.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1000&h=700"],
["Agricultural Land","Agricultural Land — Nearby","Haridwar District","1 Bigha+","https://images.pexels.com/photos/7031600/pexels-photo-7031600.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1000&h=700"]];
const services=[["Buy Property","Find your home, plot, land or commercial space from practical local options."],["Sell Property","Present your property clearly and connect with serious local buyers."],["Rent Property","Explore houses, flats and shops around Laksar and Haridwar."],["Property Guidance","Straightforward help with visits, documentation and local information."]];
function reveal(){const r=useRef<HTMLElement|null>(null);useEffect(()=>{const e=r.current;if(!e)return;const o=new IntersectionObserver(([x])=>{if(x.isIntersecting){e.classList.add("revealed");o.disconnect()}},{threshold:.1});o.observe(e);return()=>o.disconnect()},[]);return r}
export default function HomePage(){const[s,setS]=useState(0),[q,setQ]=useState(""),[menu,setMenu]=useState(false),[mouse,setMouse]=useState({x:-100,y:-100}),[hot,setHot]=useState(false),[scroll,setScroll]=useState(0);const timer=useRef<ReturnType<typeof setInterval>|null>(null),pRef=reveal(),aRef=reveal(),dRef=reveal(),cRef=reveal();const shown=useMemo(()=>props.filter(p=>p.join(" ").toLowerCase().includes(q.toLowerCase())),[q]);const reset=()=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>setS(x=>(x+1)%slides.length),5000)};useEffect(()=>{reset();const m=(e:MouseEvent)=>setMouse({x:e.clientX,y:e.clientY}),sc=()=>{const max=document.documentElement.scrollHeight-innerHeight;setScroll(max?scrollY/max*100:0)};addEventListener("mousemove",m,{passive:true});addEventListener("scroll",sc,{passive:true});return()=>{if(timer.current)clearInterval(timer.current);removeEventListener("mousemove",m);removeEventListener("scroll",sc)}},[]);const go=(n:number)=>{setS((n+slides.length)%slides.length);reset()};const active=slides[s];return <main id="top"><div className="scroll-progress-bar" style={{width:`${scroll}%`}}/><div className={`cursor-dot ${hot?"hovering":""}`} style={{left:mouse.x,top:mouse.y}}/><div className={`cursor-ring ${hot?"hovering":""}`} style={{left:mouse.x,top:mouse.y}}/><div className="cursorGlow" style={{left:mouse.x,top:mouse.y}}/>
<header className="nav"><a className="brand" href="#top"><span className="brandMark"><Home size={18}/></span><span>LRJ <b>PROPERTIES</b></span></a><nav className={menu?"navLinks open":"navLinks"}>{["properties","services","about","testimonials","contact"].map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)} onMouseEnter={()=>setHot(true)} onMouseLeave={()=>setHot(false)}>{x[0].toUpperCase()+x.slice(1)}</a>)}</nav><a className="navCta" href={`tel:${phone}`}><Phone size={16}/> Call</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section className="hero heroSlider" onWheel={e=>Math.abs(e.deltaY)>45&&go(s+(e.deltaY>0?1:-1))}>{slides.map((x,i)=><div key={x.image+i} className={`heroBackdropLayer ${i===s?"active":""}`}><div className="heroBackdrop" style={{backgroundImage:`url(${x.image})`,transform:`translate3d(${mouse.x*.01}px,${mouse.y*.006}px,0) scale(1.08)`}}/></div>)}<div className="heroShade"/><div className="heroGrid"/><div className="heroGlow"/><div className="heroParticles">{Array.from({length:14}).map((_,i)=><i key={i} style={{left:`${i*7+5}%`,animationDelay:`-${i*.5}s`}}/>)}</div><div className="heroContent slideIn" key={s}><div className="eyebrow"><Sparkles size={14}/>LOCAL PROPERTY • LAKSAR / HARIDWAR</div><h1>{active.title}<br/><em>{active.accent}</em></h1><p>{active.text}</p><div className="heroActions"><a className="primary btn-magnetic" href="#properties">Explore properties <ArrowRight size={17}/></a><a className="secondary" href={wa} target="_blank" rel="noreferrer">WhatsApp us</a></div><div className="trust"><span><CheckCircle2/> Local guidance</span><span><ShieldCheck/> Clear communication</span></div></div><div className="heroVisual"><div className="visualFrame"><img src={active.image} alt="Local property"/><div className="visualLabel"><small>0{s+1} / 04</small><strong>LOCAL PROPERTY</strong></div></div><div className="parallaxCard"><span>Property search</span><strong>Laksar • Haridwar</strong><i>Local-first</i></div></div><div className="verticalPager">{slides.map((_,i)=><button key={i} className={i===s?"active":""} onClick={()=>go(i)}><span>0{i+1}</span></button>)}</div><div className="heroScroll">⌄ DRAG / SCROLL TO EXPLORE</div><div className="heroProgress"><div key={s}/></div></section>
<section className="strip marquee"><div className="marqueeTrack">{["🏠 Houses","📐 Residential Plots","🌾 Agricultural Land","🏢 Commercial Spaces","📍 Laksar","📍 Haridwar","📍 Roorkee","🤝 Local Guidance","📋 Documentation","🔐 Clear Dealings","🏠 Houses","📐 Residential Plots"].map((x,i)=><div key={i}>{x}<span>✦</span></div>)}</div></section>
<section id="properties" className="section revealSection" ref={pRef as React.RefObject<HTMLElement>}><div className="sectionHead"><div><span className="kicker">CURRENT OPTIONS</span><h2>Explore local properties</h2></div><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search property..."/></div></div><div className="cards">{shown.map(p=><article className="card tilt-card revealCard" key={p[1]}><div className="propertyVisual v0"><span>{p[0]}</span><img src={p[4]} alt={p[1]}/></div><div className="cardBody"><span className="location"><MapPin size={14}/>{p[2]}</span><h3>{p[1]}</h3><p>{p[3]}</p><div className="cardFoot"><strong>Contact for price</strong><a href="#contact">Enquire <ArrowRight size={15}/></a></div></div></article>)}</div></section>
<section id="about" className="about revealSection" ref={aRef as React.RefObject<HTMLElement>}><div className="aboutVisual"><div className="mapLines"/><div className="pin"><MapPin/></div><span>LAKSAR • HARIDWAR</span><div className="mapLabel">LOCAL MARKET FOCUS</div></div><div className="aboutText"><span className="kicker">ABOUT LRJ</span><h2>A local approach to finding the right property.</h2><p>We focus on useful information, honest communication and properties that make sense for everyday buyers, families and land investors.</p><div className="checks"><span><CheckCircle2/> Local area focus</span><span><CheckCircle2/> Property guidance</span><span><CheckCircle2/> Visit coordination</span></div></div></section>
<section id="services" className="darkSection revealSection" ref={dRef as React.RefObject<HTMLElement>}><div className="kicker">WHAT WE DO</div><h2>Simple property help,<br/><em>without the confusion.</em></h2><div className="serviceGrid">{services.map((x,i)=><div className="service" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><ArrowRight className="serviceArrow" size={18}/></div>)}</div></section>
<section id="testimonials" className="section revealSection" ref={cRef as React.RefObject<HTMLElement>}><div className="sectionHead"><div><span className="kicker">TESTIMONIALS</span><h2>What our clients say</h2></div></div><div className="cards">{[["R","Rajesh Kumar","Laksar"],["S","Sunita Devi","Haridwar"],["A","Amit Sharma","Roorkee"],["P","Pooja Singh","Laksar"]].map(x=><article className="card" key={x[1]}><div className="cardBody"><div className="quote">“</div><div className="stars">★★★★★</div><p>Clear communication, practical local guidance and a straightforward property experience.</p><div className="location"><b>{x[0]}</b> {x[1]} • {x[2]}</div></div></article>)}</div></section>
<section id="contact" className="contact revealSection"><div><span className="kicker">LET&apos;S TALK</span><h2>Have a property in mind?</h2><p>Call or WhatsApp directly, or send us a property inquiry and we&apos;ll follow up.</p></div><div className="contactActions"><a className="primary" href={`tel:${phone}`}><Phone size={17}/> Call now</a><a className="secondary" href={wa} target="_blank" rel="noreferrer">WhatsApp</a></div></section>
<section id="inquiry" className="inquirySection"><InquiryForm /></section>
<div className="floating"><button onClick={()=>scrollTo({top:0,behavior:"smooth"})}>↑</button><a href={`tel:${phone}`}>☎</a><a href={wa} target="_blank" rel="noreferrer" className="wa">◔</a></div><footer><div className="brand"><span className="brandMark"><Home size={17}/></span><span>LRJ <b>PROPERTIES</b></span></div><p>© 2026 LRJ Properties · Laksar & Haridwar</p></footer></main>}
